[global]
limits = { forms = 32768 }
port = 8000
keep_alive = 5
read_timeout = 5
write_timeout = 5

[global.databases]
adventskalender = { url = "postgres://debuguser:debugpassword@127.0.0.1/adventskalender", pool_size = 25 }

[development]
address = "localhost"
workers = 1
log = "debug"

[production]
address = "0.0.0.0"
workers = 2
log = "critical"
# secret_key = [randomly generated at launch]