name: Build and test backend
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libpq
      run: sudo apt-get install -y libpq-dev
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
    - name: Install the required rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: Build the backend
      run: cargo build --verbose
      working-directory: adventskalender-backend
    - name: Check code style
      run: cargo fmt --all -- --check
      working-directory: adventskalender-backend
    - name: Run tests
      run: cargo test --verbose
      working-directory: adventskalender-backend
